#!/usr/bin/env bash

dir="$(dirname $0)/.."

envfile="$dir/.env"
venvfile="$dir/venv/bin/activate"
logfile="$dir/logs.log"

[ -f "$envfile" ] && export $(cat "$envfile" | xargs) || echo "No $envfile file found" >&2
[ -f "$venvfile" ] && source "$venvfile" 2> /dev/null || echo "$venvfile not found" >&2
npm run start >> "$logfile" 2>&1
