#!/usr/bin/env bash

dir="$(dirname $0)"

envfile="$dir/../.env"

[ -f "$envfile" ] && export $(cat "$envfile" | xargs) || echo "No $envfile file found" >&2
[ -f venv/bin/activate ] && source venv/bin/activate 2> /dev/null || echo "venv not found" >&2
npm run start >> logs.log 2>&1
