#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
RESET='\033[0m'

npm i &&
python3 -m venv venv &&
source venv/bin/activate &&
pip install -r requirements.txt &&
deactivate &&
echo $GREEN"Setup completed"$RESET >&2 ||
echo $RED"Setup failed"$RESET >&2
